---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
          docker compose version  # Kiểm tra xem Docker Compose đã cài thành công chưa

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker compose build  # Dùng `docker compose` thay vì `docker-compose`

      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py test"

      - name: Run Lint
        run: docker compose run --rm app sh -c "flake8"
