---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker services
        run: docker compose up -d --build  # Sử dụng "docker compose" thay vì "docker-compose"

      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Run Lint
        run: docker compose run --rm app sh -c "flake8"

      - name: Stop and clean up
        run: docker compose down
